create table carta_di_credito (
	numero varchar(16) primary key not null,
	intestatario varchar(255) not null,
	scadenza date not null,
	cvv int not null
);

create table utente (
	email varchar(255) primary key not null,
	password varchar(255) not null,
	nome varchar(255) not null,
	cognome varchar(255) not null
);

create table indirizzo (
	id int generated by default as identity primary key,
	via varchar(255) not null,
	numero_civico int not null,
	cap varchar(5) not null,
	citta varchar(255) not null,
	stato varchar(255) not null
);

create table indirizzo_spedizione (
	utente varchar(255) not null,
	indirizzo int not null,
	primary key (utente, indirizzo),
	foreign key (utente) references utente(email),
	foreign key (indirizzo) references indirizzo(id)

);

create table lista (
	id int generated by default as identity primary key,
	nome varchar(255) not null,
	utente varchar(255) not null,
	data_creazione date not null,
	data_modifica date not null,
	foreign key (utente) references utente(email)
);

create table ordine (
	lista int primary key not null,
	indirizzo int not null,
	provider varchar(255) not null,
	status varchar(255) not null,
	foreign key (lista) references lista(id),
	foreign key (indirizzo) references indirizzo(id)
);

create table categoria (
	nome varchar(255) primary key not null,
	descrizione varchar(255) not null
);

create table prodotto (
	id int generated by default as identity primary key,
	nome varchar(255) not null,
	descrizione varchar(255) not null,
	prezzo float not null,
	quantita int not null,
	tag varchar(255) not null,
	foreign key (tag) references categoria(nome)
);

create table contenuto (
	lista int not null,
	prodotto int not null,
	quantita int not null,
	primary key (lista, prodotto),
	foreign key (lista) references lista(id),
	foreign key (prodotto) references prodotto(id)
);
